-- Flyway migration: create supermarket and product tables (Postgres compatible)

CREATE TABLE IF NOT EXISTS supermarket (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(1024),
    logo_url VARCHAR(1024),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    image_url VARCHAR(1024),
    name VARCHAR(255) NOT NULL,
    brand VARCHAR(255),
    price NUMERIC(10,2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'EUR',
    supermarket_id BIGINT,
    description TEXT,
    quantity INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_product_supermarket FOREIGN KEY (supermarket_id) REFERENCES supermarket(id)
);
