-- Flyway migration: create supermarket_repo table to store repo URL ranges for supermarkets

CREATE TABLE IF NOT EXISTS supermarket_page (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    supermarket_id BIGINT NOT NULL,
    url VARCHAR(2048) NOT NULL,
    date_from DATE NOT NULL,
    date_to DATE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_supermarket_page_supermarket FOREIGN KEY (supermarket_id) REFERENCES supermarket(id)
);

-- Optional index for lookups by supermarket and date range
CREATE INDEX IF NOT EXISTS idx_supermarket_page_supermarket_id ON supermarket_page(supermarket_id);

